## Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
arr = np.arange(2, 50, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

## Questions 2:

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
a = [3,2,1,4,5]
b = [6,10,8,9,7]

arr1 = np.array(a)
arr2 = np.array(b)

print(arr1)
print(arr2)

#Type
print(type(arr1))
print(type(arr2))

#Concatenate
arr3 = np.concatenate((arr1, arr2))
print(arr3)

#Sort
arr4 = np.sort(arr3)
print(arr4)

[3 2 1 4 5]
[ 6 10  8  9  7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 3  2  1  4  5  6 10  8  9  7]
[ 1  2  3  4  5  6  7  8  9 10]


## Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr = np.arange(12).reshape(3,4)
print(arr)

# Dimension of ndarray
print(arr.ndim)

# Size of ndarray
print(arr.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
12


## Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
arr = np.arange(12)
print(arr.shape)

# 2d array for row
arr1 = arr[np.newaxis, :]
print(arr1)
print(arr1.shape)

# 2d array for column
arr2 = arr[:, np.newaxis]
print(arr2)
print(arr2.shape)

(12,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(1, 12)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(12, 1)


## Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack

In [6]:
arr1 = np.square([1,2,3,-4,5])
arr2 = np.square([12,15,14,-18,20])
print(arr1)
print(arr2)

[ 1  4  9 16 25]
[144 225 196 324 400]


In [7]:
np.vstack((arr1,arr2)) # Vertically stacked

array([[  1,   4,   9,  16,  25],
       [144, 225, 196, 324, 400]], dtype=int32)

In [8]:
np.hstack((arr1,arr2)) # Horizontally stacked

array([  1,   4,   9,  16,  25, 144, 225, 196, 324, 400], dtype=int32)

## Questions 6:

How to get unique items and counts of unique items?

In [9]:
arr = np.array([1,2,4,5,7,8,8,7,5,4,1,2,3,6,9,6,9,3,5,11,4,22,55,44,14,18,23,22])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  2]
 [ 4  3]
 [ 5  3]
 [ 6  2]
 [ 7  2]
 [ 8  2]
 [ 9  2]
 [11  1]
 [14  1]
 [18  1]
 [22  2]
 [23  1]
 [44  1]
 [55  1]]
